### ISSUE TITLE
What's different between *_raw, *_processed, *_numpy?

### ISSUE THREAD

**Issue by shawrby** [valeoai/carrada_dataset#1]
Thank you for making the radar data set public.

I'm trying to develop an algorithm using CARRADA dataset.
What is the difference between '*_raw, *_processed, and *_numpy' files?

Thanks in advance for your reply.

**Comment by ArthurOuaknine** [comment]
Hello.
I apologise for the late answer.
For both files, the RAD tensor has been aggregated using a sum over the third axis.
We applied a log transformation on the representation to generate the *_processed files.
The *_numpy are another preprocessing using a max instead of the sum for the range-angle, and it is a dupplicate of the *_processed for range-Doppler. I will homogenise the name of the files.
You can recover these processed views using the RAD tensors which have been released lately.
I hope it will help.
Best
