### ISSUE TITLE
Angle resolution problem

### ISSUE THREAD

**Issue by ZHOUYI1023** [valeoai/carrada_dataset#4]
Hello, in your paper, the angle resolution of your radar is 0.7 degree. According to the equation, the resolution should roughly equal 2/N rad. That indicates you have a large number of antennas. Do you use the cascaded radar platform? Or a calculation mistake?

**Comment by ArthurOuaknine** [comment]
Hello, it is not the angle resolution of the radar but the FFT angle resolution which is mentionned to be 0.7 deg in the paper.
It means that, in the angle dimension (in the RA or the RAD representation), each bin correspond to 0.7deg resolution.
However the angular resolution of the radar can be computed with the formula at the end of section 2.B., roughly equal to 2/N rad.
So there are redundant information in the angle axis because the FFT resolution is lower than the actual angular resolution of the sensor.

I hope it will help.
Best.
